# Generated by Django 6.0.3 on 2026-03-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constraint', models.CharField(choices=[('none', 'Aucune contrainte'), ('tn_only', 'Nuit uniquement'), ('no_tn', 'Jamais la nuit'), ('tm_only', 'Matin uniquement'), ('tt_only', 'Après-midi uniquement')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
