# Generated by Django 6.0.3 on 2026-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='constraint',
        ),
        migrations.AddField(
            model_name='employee',
            name='puede_TM',
            field=models.BooleanField(default=True, verbose_name='TM'),
        ),
        migrations.AddField(
            model_name='employee',
            name='puede_TN',
            field=models.BooleanField(default=True, verbose_name='TN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='puede_TT',
            field=models.BooleanField(default=True, verbose_name='TT'),
        ),
    ]
