# Generated by Django 6.0.3 on 2026-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_constraint_employee_puede_tm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['departamento', 'name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='departamento',
            field=models.CharField(choices=[('produccion', 'Producción'), ('acondicionamiento', 'Acondicionamiento')], default='produccion', max_length=20),
        ),
    ]
