# Generated by Django 6.0.3 on 2026-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_employee_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='en_baja',
            field=models.BooleanField(default=False, verbose_name='En arrêt maladie'),
        ),
    ]
