# Generated by Django 6.0.3 on 2026-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_en_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.AddField(
            model_name='employee',
            name='baja_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin baja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='baja_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio baja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='en_baja',
            field=models.BooleanField(default=False, verbose_name='En baja'),
        ),
    ]
