# Generated by Django 6.0.3 on 2026-03-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('shift', models.CharField(choices=[('TM', 'Matin'), ('TT', 'Après-midi'), ('TN', 'Nuit')], max_length=2)),
                ('is_manual', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['year', 'month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
