# Generated by Django 6.0.3 on 2026-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.CharField(choices=[('TM', 'Matin'), ('TT', 'Après-midi'), ('TN', 'Nuit'), ('BJ', 'Baja')], max_length=2),
        ),
    ]
